In [1]:
from google.colab import drive
drive.mount('/content/drive')

import pandas as pd
import numpy as np

Mounted at /content/drive

In [3]:
#Carregando customer_features.csv

customer_features = pd.read_csv("/content/drive/MyDrive/Consumo inteligente hackathon/data/processed_dados tratados/customer_features.csv")
customer_features.head()

,CustomerID,Recency,Frequency,Monetary,TotalQuantity,AvgUnitPrice,UniqueProducts,CountryCount,AvgInvoiceTicket,MaxInvoiceTicket,AvgSpendPerPurchase,AvgQuantityPerPurchase
0,12346.0,326,1,77183.60,74215,1.040000,1,1,77183.600000,77183.60,77183.600000,74215.000000
1,12347.0,2,7,4310.00,2458,2.644011,103,1,615.714286,1294.32,615.714286,351.142857
2,12348.0,75,4,1797.24,2341,5.764839,22,1,449.310000,892.80,449.310000,585.250000
3,12349.0,19,1,1757.55,631,8.289041,73,1,1757.550000,1757.55,1757.550000,631.000000
4,12350.0,310,1,334.40,197,3.841176,17,1,334.400000,334.40,334.400000,197.000000

In [4]:
#Validação

customer_features.shape

(4338, 12)

In [6]:
# Importando bibliotecas para clustering
from sklearn.preprocessing import StandardScaler
from sklearn.cluster import KMeans

In [8]:
# Selecionando e preparando as features para clustering
features=customer_features[["Recency","Frequency","Monetary","AvgInvoiceTicket"]].copy()
features=features.fillna(0)

features.head()

   Recency  Frequency  Monetary  AvgInvoiceTicket
0      326          1  77183.60      77183.600000
1        2          7   4310.00        615.714286
2       75          4   1797.24        449.310000
3       19          1   1757.55       1757.550000
4      310          1    334.40        334.400000

In [9]:
#Padronizando os dados

scaler = StandardScaler()
features_scaled= scaler.fit_transform(features)

In [13]:
# Aplicando o algoritmo KMeans para clustering e atribuindo os resultados
kmeans= KMeans(n_clusters=4,random_state=42)
customer_features["Cluster"]=kmeans.fit_predict(features_scaled)

customer_features.head()

,CustomerID,Recency,Frequency,Monetary,TotalQuantity,AvgUnitPrice,UniqueProducts,CountryCount,AvgInvoiceTicket,MaxInvoiceTicket,AvgSpendPerPurchase,AvgQuantityPerPurchase,Cluster
0,12346.0,326,1,77183.60,74215,1.040000,1,1,77183.600000,77183.60,77183.600000,74215.000000,1
1,12347.0,2,7,4310.00,2458,2.644011,103,1,615.714286,1294.32,615.714286,351.142857,0
2,12348.0,75,4,1797.24,2341,5.764839,22,1,449.310000,892.80,449.310000,585.250000,0
3,12349.0,19,1,1757.55,631,8.289041,73,1,1757.550000,1757.55,1757.550000,631.000000,0
4,12350.0,310,1,334.40,197,3.841176,17,1,334.400000,334.40,334.400000,197.000000,2

In [14]:
#Quantidade de clientes por cluster

customer_features["Cluster"].value_counts()

Cluster
0    3225
2    1088
3      23
1       2
Name: count, dtype: int64

In [16]:
# Criando o perfil de cada cluster calculando a média das features
cluster_profile=customer_features.groupby("Cluster")[["Recency","Frequency","Monetary","AvgInvoiceTicket"]].mean()
cluster_profile

            Recency  Frequency       Monetary  AvgInvoiceTicket
Cluster
0         41.231938   4.690233    1907.467213        391.885957
1        163.500000   1.500000  122828.050000      80709.925000
2        246.303309   1.581801     524.399734        327.006549
3          6.304348  73.130435   84505.353478       1622.094617

In [18]:
# Salvando os dados do cliente com os clusters atribuídos em um novo arquivo CSV
customer_features.to_csv(
    "/content/drive/MyDrive/Consumo inteligente hackathon/data/processed_dados tratados/customer_features_cluster.csv",
    index=False,
)

print("Arquivo customer_features_cluster.csv salvo no Drive!")

Arquivo customer_features_cluster.csv salvo no Drive!